### ISSUE TITLE
Ability to rename torrents

### ISSUE THREAD

**Issue by AgathaSorceress** [intuis/rustmission#122]
Hi! I've been enjoying using this client a lot :) I think it'd be great to be able to rename torrents, either through a global keybinding or in the Details view.

**Comment by micielski** [comment]
> I've been enjoying using this client a lot :)

:D 

I'll try to implement this by the end of this weekend

**Comment by micielski** [comment]
Okay, I think it's done :)

To make use of this, you have to bind `Rename` action to a key under `[torrents_tab]` in `keymap.toml` like this:
```toml
[torrents_tab]
keybindings = [
    { on = "r", action = "Rename" },
]
```
