### ISSUE TITLE
Categories, default_dir mandatory?

### ISSUE THREAD

**Issue by slundi** [intuis/rustmission#139]
Hello

I was making some categories:
```toml
# Colors: https://ratatui.rs/examples/style/colors/
# Example category:
# [[categories]]
# name = "Classical Music"             # required
# icon = "[M]"                         # optional, default: ""
# default_dir = "/mnt/Music/Classical" # optional, default: transmission's default
# color = "Green"                      # optional, default: "White"

[[categories]]
name = "Movie"
icon = "🎬"
color = "#000080"

[[categories]]
name = "TV"
icon = "📺"
color = "Orange"

[[categories]]
name = "Anime"
icon = "🐈" 
color = "Green"

[[categories]]
name = "Game"
icon = "🎮"
color = "Red"

[[categories]]
name = "Music"
icon = "📀"
color = "Yellow"
```

But when I'm trying to rust `rustmission` I got the following error:
```
Failed to parse config located at "/home/me/.config/rustmission/categories.toml"

Caused by:
    TOML parse error at line 9, column 1
      |
    9 | [[categories]]
      | ^^^^^^^^^^^^^^
    missing field `default_dir`
```
