### ISSUE TITLE
feat: rss feed background refresh

### ISSUE THREAD

**Issue by aidanaden** [intuis/rustmission#51]
background thread that downloads torrents from subscribed RSS feeds and refreshes every 30s - all can be configured in config, e.g.

```toml
[[rss]]
url = "https://xyz/rss"
# regex string filter
filter = "<insert regex string>"
# in seconds
refresh = 30 
```
