### ISSUE TITLE
Config used glyphs

### ISSUE THREAD

**Issue by Locorock** [intuis/rustmission#82]
I'd be nice if the glyphs used in the tui were configurable. This would allow the app to both work with fonts other than nerdsfonts (phospor, font-specific, etc ) and in terminals without unicode support (xterm). In my case i'm using a bitmap font with quite a few unicode glyphs ([Cozette](https://github.com/slavfox/Cozette)) but most of them still appear unavailable.

![grim-2024-ago-07-16_51_43](https://github.com/user-attachments/assets/d3da3de3-de0f-4012-b1bb-ab37715c91bb)
![grim-2024-ago-07-16_53_32](https://github.com/user-attachments/assets/ca6d6838-318b-4971-a5d6-cfdee13ab683)

An example for a possible configuration would be: 
```toml
[icons]
download_speed = '▼'
upload_speed = '▲'
and_so_on = ''
```

P.S. torrents in the images are completely AI generated btw. I would never steal a car.

**Comment by micielski** [comment]
@Locorock 
Currently the config in #89 looks like this:
```toml
[icons]
upload = ""
download = ""
arrow_left = ""
arrow_right = ""
arrow_up = ""
arrow_down = ""
triangle_right = "▶"
triangle_down = "▼"
file = ""
disk = "󰋊"
help = "󰘥"
success = ""
failure = ""
searching = ""
verifying = "󰑓"
loading = "󱥸"
pause = "󰏤"
idle = "󱗼"
provider_disabled = "󰪎"
provider_category_general = ""
provider_category_anime = "󰎁"
``` 
Could you tell me with what values would you override these icons so I can include them in the config as an alternative to nerd fonts? If you have no alternatives to some, you can leave them as they are, thanks!
