### ISSUE TITLE
categories/labels

### ISSUE THREAD

**Issue by micielski** [intuis/rustmission#9]
with default directories to be saved in

**Comment by micielski** [comment]
Something like this in labels.toml:
```toml
[[label]]
name = "Classical Music" # Required (not sure if transmission allows for labels with spaces)
color = "Green" # OPTIONAL, default would be white
default_dir = "/some/directory/" # OPTIONAL, default would be default (transmission's daemon default)

[[label]]
name = "Just another category"
color = "#abc"
default_dir = "/another/dir"
```
This file would be just next to the config.toml file, created by default but with example labels commented out

**Comment by micielski** [comment]
It'd introduce a new column "Label", but hidden by default (if labels.is_empty())

**Comment by micielski** [comment]
> It'd introduce a new column "Label", but hidden by default (if labels.is_empty())

Instead of a column there could be also a prefix that would be alongside the name, just added before every torrent name (it would be also colored).

```toml
[[label]]
name = "Music"
prefix = "M" # could be also a nerd fonts icon, optional
color = "#abc"
default_dir = "/another/dir"
```

and in config.toml:

```toml
[general]
enable_label_column = true
enable_label_prefix = true
```

these of course would do nothing if there are no labels
